runtime: php73

env_variables:
  ## Put production environment variables here.
  APP_KEY: vvqmQrd7obaCUHqd12rPLm77S1l95ZnaF83iZ0Am1wE=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie